name: Add/update Submodule in gh-pages

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add or update submodule
        env:
          BRANCH_NAME: ${{ inputs.pr_number }}
        run: |
          echo ${{ env.BRANCH_NAME }}
          if [ -d "${{ env.BRANCH_NAME }}" ]; then
            echo "Submodule exists. Updating..."
            git submodule update --init --remote "${{ env.BRANCH_NAME }}"
          else
            echo "Adding submodule..."
            git submodule add -b "${{ env.BRANCH_NAME }}" https://github.com/ServiceCanada/wet-boew-demos.git "${{ env.BRANCH_NAME }}"
          fi

      - name: Commit changes
        run: |
          ls
          git add .
          git commit -m "Update or add submodule in gh-pages" --allow-empty
          git push origin gh-pages
