name: Add/update Submodule in gh-pages

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  add-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Add or update submodule
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [ -d "$BRANCH_NAME" ]; then
            echo "Submodule exists. Updating..."
            git submodule update --init --remote "$BRANCH_NAME"
          else
            echo "Adding submodule..."
            git submodule add https://github.com/ServiceCanada/wet-boew-demos.git "$BRANCH_NAME"
          fi

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update or add submodule in gh-pages" --allow-empty
          git push origin gh-pages
