name: Generate demo on user input

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request branch name (e.g., pr-1234)'
        required: true
        type: string

jobs:
  push-demo-files-trigger:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/demo-from-pr.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number }}

  push-demo-files-push:
    if: github.event_name == 'push'
    uses: ./.github/workflows/demo-from-pr.yml
    with:
      pr_number: ${{ github.ref_name}}
    
  update-submodules-trigger:
    if: github.event_name == 'workflow_dispatch'
    needs: push-demo-files-trigger
    uses: ./.github/workflows/add-submodule.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number }}

  update-submodules-push:
    if: github.event_name == 'push'
    needs: push-demo-files-push
    uses: ./.github/workflows/add-submodule.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number }}