name: Generate demo on push

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  push-demo-files:
    uses: ./.github/workflows/demo-from-pr.yml
    with:
      pr_number: ${{ github.ref_name }}
    
  update-submodules:
    needs: push-demo-files
    uses: ./.github/workflows/add-submodule.yml
    with:
      pr_number: ${{ github.ref_name }}