on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: string

jobs:
  push-demo-files:
    uses: ./.github/workflows/demo-from-pr.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number }}
    
  update-submodules:
    uses: ./.github/workflows/add-submodule.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number }}